spring.application.name=booking-system

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/booking_db
spring.datasource.username=root
spring.datasource.password=Kaibalya@12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

app.jwt.secret=8fK2mP9xQ7vL4nR6tY3wZ1aB5cD8eF0gH2jK6mN9pQ4sT7uV
app.jwt.expiration-ms=86400000